package controller;

// imports
import model.EmptyInputException;
import model.PalindromeModel;
import view.PalindromeView;
import model.Mismatch;
import model.AnalysisStatus;

// gui
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.util.List;

/**
 * The PalindromeController class acts as the Controller in the MVC architecture.
 * It connects the {@link PalindromeModel} (business logic) and {@link PalindromeView} (user interface),
 * managing user interactions and updating the view with results from the model.
 * 
 * The controller listens for user actions, such as clicking the "Check" button,
 * and triggers palindrome analysis based on user input or command-line arguments.
 * 
 * @version 1.2
 * @author Jakub Tomaszewski
 */
public class PalindromeController {


    private PalindromeModel model;
    private PalindromeView view;

    /**
     * Constructs a new PalindromeController that connects the given model and view.
     * It also initializes event listeners and optionally performs an immediate analysis
     * if command-line arguments are provided.
     * 
     * @param model the {@link PalindromeModel} instance used for palindrome analysis
     * @param view the {@link PalindromeView} instance representing the graphical interface
     * @param args optional command-line arguments that may contain a text to analyze
     */
    public PalindromeController(PalindromeModel model, PalindromeView view, String[] args) {
        this.model = model;
        this.view = view;


        this.view.getCheckButton().addActionListener(new CheckButtonListener());
        
        if (args.length > 0) {
            String inputFromArgs = String.join(" ", args);
            
            performAnalysis(inputFromArgs);
        }
    }

    /**
     * Inner class that handles the "Check" button click event.
     * When triggered, it retrieves the text entered by the user and starts the analysis.
     */
    class CheckButtonListener implements ActionListener {
        @Override
        /**
         * Invoked when the "Check" button is pressed.
         *
         * @param e the event generated by clicking the button
         */
        public void actionPerformed(ActionEvent e) {

            performAnalysis(view.getInputValue());
        }
    }

/**
     * Performs palindrome analysis on the given raw input.
     * This method normalizes the input, clears previous results from the view,
     * calls the model to analyze the text, and then updates the view
     * with the analysis result and any mismatched characters if found.
     *
     * @param rawInput the input string to analyze
     */
private void performAnalysis(String rawInput) {
        
        DefaultTableModel tableModel = view.getTableModel();
        tableModel.setRowCount(0); 
        view.setStatusText(" "); 
        view.showTable(false); 
        
        view.setInputText(rawInput);
        
        String input = rawInput.replaceAll("\\s+", "").toLowerCase();

        try {
            model.analyze(input);

            AnalysisStatus status = model.getStatus();
            
            String statusText = "'" + input + "' (length:: " + input.length() + ")";
            
            switch (status) {
                case PALINDROME:
                    view.setStatusText(statusText + " IS palindrome.");
                    view.showTable(false); 
                    break;
                
                case NOT_PALINDROME:
                    view.setStatusText(statusText + " IS NOT palindrome. Differs:");
                    
                    List<Mismatch> differences = model.getDifferences();
                    
                    differences.stream()
                        .map(mismatch -> new Object[] {
                            mismatch.pos1(),
                            mismatch.char1(),
                            mismatch.pos2(),
                            mismatch.char2()
                        })
                        .forEach(tableModel::addRow);
                    
                    view.showTable(true); 
                    break;
                
                case EMPTY:
                    view.setStatusText("Empty string.");
                    break;
            }

        } catch (EmptyInputException ex) {
            JOptionPane.showMessageDialog(
                    view.getFrame(), 
                    "error: " + ex.getMessage(),
                    "input error", 
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
}